name: Nightly Pipeline

on:
    push:
        branches: [dev]

jobs:
    build:
        env:
            VERSION: "${{ vars.NIGHTLY_MAJOR_VERSION }}.${{ github.run_number }}"
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

        permissions: write-all
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Development workflow
              if: ${{ env.BRANCH_NAME }} == dev
              run: |
                  echo "I am a dev workflow"

            - name: Main workflow
              if: ${{ env.BRANCH_NAME }} == main
              run: |
                  echo "I am a main workflow"

            - name: Versioning
              run: |
                  echo 'export var version = "${{ env.VERSION }}";' > ./src/version.tsx
                  echo 'export var commit = "${{ github.GITHUB_SHA }}";' >> ./src/version.tsx
                  echo 'export var actor = "${{ github.GITHUB_ACTOR }}";' >> ./src/version.tsx
                  cat ./src/version.tsx
            - run: npm i
            - name: Update my-file.json description
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: manifest.json
                  field: version
                  value: ${{ env.VERSION }}

            - run: npm run build

            - name: cleanup
              run: |
                  mv ./node_modules/normalize.css/ ./normalize.css/
                  mv ./node_modules/@blueprintjs/ ./@blueprintjs/
                  rm -rf ./node_modules
                  mkdir ./node_modules
                  mv ./normalize.css/ ./node_modules/normalize.css/
                  mv ./@blueprintjs/ ./node_modules/@blueprintjs/
                  rm -rf ./src
                  rm -rf ./public
                  rm package-lock.json
                  rm package.json
                  rm tsconfig.json
                  rm webpack.config.js
                  rm logo.afdesign

            - id: packExtensionDir
              uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
              with:
                  extensionDir: "."
                  zipFilePath: "build/package.zip"

            - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
              with:
                  # zip file made at the packExtensionDir step
                  zipFilePath: "build/package.zip"
                  crxFilePath: "crx-file.crx"
                  privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

            - name: Rename to release
              run: mv ./build/package.zip ./build/Foundry-Upgrade-Chrome-Extension-${{ env.VERSION }}.zip

            - name: Release Package as Pre-Repease
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "nightly_${{ env.VERSION }}"
                  prerelease: true
                  title: "Foundry-Upgrade-Chrome-Extension-${{ env.VERSION }}"
                  files: |
                      ./build/Foundry-Upgrade-Chrome-Extension-${{ env.VERSION }}.zip
