name: Node.js CI

on:
    push:
        branches: [dev]

jobs:
    build:
        permissions: write-all
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm i

            - name: Update my-file.json description
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: manifest.json
                  field: version
                  value: 1.${{ github.run_number }}

            - run: npm run build
            - run: ls
            - name: cleanup
              run: |
                  rm -rf ./node_modules
                  rm -rf ./src
                  rm -rf ./public
                  rm package-lock.json
                  rm package.json
                  rm tsconfig.json
                  rm webpack.config.js

            - id: packExtensionDir
              uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
              with:
                  extensionDir: "."
                  zipFilePath: "build/package.zip"

            - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
              with:
                  # zip file made at the packExtensionDir step
                  zipFilePath: "build/package.zip"
                  crxFilePath: "crx-file.crx"
                  privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

            - name: Rename to release
              run: mv ./build/package.zip ./build/Foundry-Upgrade-Chrome-Extension-1.${{ github.run_number }}.zip

            - name: Release Package as Pre-Repease
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "beta"
                  prerelease: true
                  title: "Foundry-Upgrade-Chrome-Extension-1.${{ github.run_number }}"
                  files: |
                      ./build/Foundry-Upgrade-Chrome-Extension-1.${{ github.run_number }}.zip
