name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: ls
    - name: cleanup
      run: |
        rm -rf node_modules
        rm -rf src
        rm package-lock.json
        rm package.json
        rm tsconfig.json
        rm webpack.config.js

    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: '.'
        zipFilePath: 'build/extension.zip'

    - name: Release Package as Pre-Repease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Foundry-Upgrade-${{ github.run_number }}"
          files: |
            'build/extension.zip'

    - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
      with:
        # zip file made at the packExtensionDir step
        zipFilePath: 'build/extension.zip'
        crxFilePath: 'build/extension.crx'
        privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
        # The following is optional if you need update.xml file
        updateXmlPath: 'build/update.xml'
        updateXmlCodebaseUrl: 'https://server.com/extension.crx'
