name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: ls
    - name: cleanup
      run: |
        rm -rf ./node_modules
        rm -rf ./src
        rm -rf ./public
        rm package-lock.json
        rm package.json
        rm tsconfig.json
        rm webpack.config.js

    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: '.'
        zipFilePath: 'build/package.zip'

    - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
      with:
        # zip file made at the packExtensionDir step
        zipFilePath: 'build/package.zip'
        crxFilePath: 'crx-file.crx'
        privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

    - name: Rename to release
      run: mv ./build/package.zip ./build/Foundry-Upgrade-Chrome-Extension-0.${{ github.run_number }}.zip

    - name: Release Package as Pre-Repease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Foundry-Upgrade-Chrome-Extension-0.${{ github.run_number }}"
          files: |
            ./build/Foundry-Upgrade-Chrome-Extension-0.${{ github.run_number }}.zip
            
    - name: Push to store
      uses: Klemensas/chrome-extension-upload-action@$v1
      with:
        refresh-token: "${{ secrets.REFRESH_TOKEN }}"
        client-id: "${{ secrets.CLIENT_ID }}"
        client-secret: "${{ secrets.CLIENT_SECRET }}"
        file-name: './build/Foundry-Upgrade-Chrome-Extension-0.${{ github.run_number }}.zip'
        app-id: 'emafkichlndjaelgikdhljjpohlomahm'
        publish: false
